// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUcvzwfZuS_GD5BEMQJVqQU_poPVx-LC4',
    appId: '1:719418946649:web:bf45097ff33a5568b62d48',
    messagingSenderId: '719418946649',
    projectId: 'aws-cat-care',
    authDomain: 'aws-cat-care.firebaseapp.com',
    storageBucket: 'aws-cat-care.firebasestorage.app',
    measurementId: 'G-T2L9MHZ5BJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAONuUNhZKlMOC-hScNNBLllHi91PUmrio',
    appId: '1:719418946649:android:becb4ad33fc3a40cb62d48',
    messagingSenderId: '719418946649',
    projectId: 'aws-cat-care',
    storageBucket: 'aws-cat-care.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpDitfEv9zaxqBa2qVWbCkhniztjbr0TA',
    appId: '1:719418946649:ios:537a93ec4581f7ceb62d48',
    messagingSenderId: '719418946649',
    projectId: 'aws-cat-care',
    storageBucket: 'aws-cat-care.firebasestorage.app',
    iosClientId: '719418946649-54q5hn41qqtb27sqk1mqugnvjogd9ukj.apps.googleusercontent.com',
    iosBundleId: 'com.example.awsApp',
  );
}
